# Flash firmware zip generated by xiaomi-flashable-firmware-creator
# (https://xiaomifirmwareupdater.com/) on marble
#
# Author: Adithya R (@ghostrider_reborn)

trap [Exception] {
    Write-Host "Error:" $_.Exception.Message
    Write-Host "`nPress enter to exit..."
    Read-Host
    Exit 1
}

# Firmware zip must be stored as firmware.zip
$ZipPath = if (Test-Path "$PSScriptRoot/firmware.zip") {
    "$PSScriptRoot/firmware.zip"
# or firmware.zip.zip because explorer doesn't show file extension by default ;)
} elseif (Test-Path "$PSScriptRoot/firmware.zip.zip") {
    "$PSScriptRoot/firmware.zip.zip"
} else {
    throw "firmware.zip not found, download and place it first."
}

Write-Host "Extracting firmware.zip..."
Expand-Archive -Path "$ZipPath" -DestinationPath "$PSScriptRoot/firmware" -Force

$partitions = @(
    "abl"
    "aop"
    "aop_config"
    "bluetooth"
    "cpucp"
    "devcfg"
    "dsp"
    "featenabler"
    "hyp"
    "imagefv"
    "keymaster"
    "modem"
    "qupfw"
    "shrm"
    "tz"
    "uefi"
    "uefisecapp"
    "xbl"
    "xbl_config"
    "xbl_ramdump"
)

foreach ($partition in $partitions) {
    Write-Host "`nFlashing $partition..."
    & "$PSScriptRoot/platform-tools-windows/fastboot" flash ${partition}_ab "$PSScriptRoot/firmware/firmware-update/$partition.img"
    if (!$?) {
        throw "Flashing $partition failed!"
    }
}

Write-Host "`nCompleted succesfully!`nPress enter to exit..."
Read-Host
